version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cloudmask-backend
    restart: unless-stopped
    networks:
      - cloudmask-network

  frontend:
    build: ./frontend
    container_name: cloudmask-frontend
    restart: unless-stopped
    ports:
      - "7337:80"
    depends_on:
      - backend
    networks:
      - cloudmask-network

networks:
  cloudmask-network:
    driver: bridge
