# GPU-enabled override for Ollama
# Usage: podman compose -f docker-compose.yml -f docker-compose.gpu.yml up -d

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
